"""
app/schemas/external_signals.py — External signal payload schemas.

External signals are supplementary context from public market, regulatory,
and operational sources outside the company's internal governance system.

Design contract:
  - External signals are ADDITIVE and SUPPLEMENTARY only.
  - They NEVER modify internal governance rules, approval chains, or risk scores.
  - They NEVER replace internal evidence registry output.
  - They provide market/regulatory/operational context to help decision reviewers
    understand the external environment in which the decision is being made.
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class ExternalSignalSource(BaseModel):
    """Provenance of a single external signal."""
    sourceId: str = Field(description="Unique identifier for the source document")
    title: str = Field(description="Full document/report title")
    sourceLabel: str = Field(description="Short display label, e.g. 'IDFA 2025', 'HHS OCR'")
    sourceType: str = Field(
        description=(
            "industry_benchmark | market_research | regulatory_guideline | "
            "operational_study | labor_regulation"
        )
    )
    recency: Optional[str] = Field(
        default=None,
        description="Recency indicator: 'recent' | 'quarterly' | 'annual' | year string e.g. '2025'"
    )


class ExternalSignal(BaseModel):
    """
    A single structured external signal relevant to the decision under governance.

    Signals are generated by Amazon Nova from company-specific context and curated sources.
    They are purely informational — they do not alter scores or approval requirements.

    Fields:
      summary         — 1 sentence: describes the external benchmark / signal itself
      decisionRelevance — 1 sentence: explains WHY the signal matters for THIS specific decision
    """
    id: str = Field(description="Unique signal identifier, e.g. 'EXT_SIG_001'")
    category: str = Field(
        description=(
            "market_benchmark | regulatory_guidance | operational_signal | "
            "trend_signal | compliance_signal"
        )
    )
    titleKo: str = Field(description="Signal title in Korean")
    titleEn: Optional[str] = Field(default=None, description="Signal title in English")
    summaryKo: str = Field(description="1 sentence Korean description of the external benchmark")
    summaryEn: Optional[str] = Field(default=None, description="1 sentence English description of the external benchmark")
    decisionRelevanceKo: str = Field(
        default="",
        description="1 sentence Korean: why this signal matters specifically for THIS decision"
    )
    decisionRelevanceEn: str = Field(
        default="",
        description="1 sentence English: why this signal matters specifically for THIS decision"
    )
    confidence: Optional[float] = Field(
        default=None, ge=0.0, le=1.0,
        description="0.5–0.9 based on source recency and relevance to the decision"
    )
    source: ExternalSignalSource
    tags: Optional[list[str]] = Field(default=None, description="Searchable tags, e.g. 'demand_trend'")


class ExternalSignalsPayload(BaseModel):
    """
    Full external signal output — attached as an additive top-level field
    on ConsolePayloadResponse.

    Signals are grouped by type:
      marketSignals      — demand, competitive, consumer trend signals
      regulatorySignals  — compliance, legal, regulatory guidance signals
      operationalSignals — supply chain, cost, operational benchmark signals

    generatedAt: ISO 8601 timestamp of when this payload was produced.
    """
    marketSignals: list[ExternalSignal] = Field(default_factory=list)
    regulatorySignals: list[ExternalSignal] = Field(default_factory=list)
    operationalSignals: list[ExternalSignal] = Field(default_factory=list)
    generatedAt: Optional[str] = None
